#version 450

layout(local_size_x = 16, local_size_y = 16) in;

layout(set = 0, binding = 0) buffer MatrixA {
    float A[];
};

layout(set = 0, binding = 1) buffer MatrixB {
    float B[];
};

layout(set = 0, binding = 2) buffer MatrixC {
    float C[];
};

layout(push_constant) uniform PushConstants {
    uint N;
} p;

void main() {
    uint row = gl_GlobalInvocationID.y;
    uint col = gl_GlobalInvocationID.x;
    uint N = p.N;

    if (row < N && col < N) {
        float sum = 0.0;
        for (uint k = 0; k < N; ++k) {
            sum += A[row * N + k] * B[k * N + col];
        }
        C[row * N + col] = sum;
    }
}
