name: Docker Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies and Type-Check
      working-directory: modules/driftnet/frontend
      run: |
        npm ci
        npm run build --if-present

    - name: Build Docker Image
      run: docker build -t driftnet-dashboard:latest -f deploy/Dockerfile .
